// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ExchangeRateErrors = &exchangeRateErrors{
	ErrUniqueExchangeRatesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "exchange_rates",
		columns: []string{"id"},
		s:       "exchange_rates_pkey",
	},

	ErrUniqueExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey: &UniqueConstraintError{
		schema:  "",
		table:   "exchange_rates",
		columns: []string{"source", "base_currency", "quote_currency", "effective_date"},
		s:       "exchange_rates_source_base_currency_quote_currency_effectiv_key",
	},
}

type exchangeRateErrors struct {
	ErrUniqueExchangeRatesPkey *UniqueConstraintError

	ErrUniqueExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey *UniqueConstraintError
}
