// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

import (
	"context"
	"errors"
	"testing"

	models "github.com/goguson/homework-april-1/internal/db/bob/bob"
	factory "github.com/goguson/homework-april-1/internal/db/bob/factory"
	"github.com/stephenafamo/bob"
)

func TestExchangeRateUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *UniqueConstraintError
		conflictMods func(context.Context, *testing.T, bob.Executor, *models.ExchangeRate) factory.ExchangeRateModSlice
	}{
		{
			name:        "ErrUniqueExchangeRatesPkey",
			expectedErr: ExchangeRateErrors.ErrUniqueExchangeRatesPkey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.ExchangeRate) factory.ExchangeRateModSlice {
				shouldUpdate := false
				updateMods := make(factory.ExchangeRateModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewExchangeRateWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.ExchangeRateModSlice{
					factory.ExchangeRateMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniqueExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey",
			expectedErr: ExchangeRateErrors.ErrUniqueExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.ExchangeRate) factory.ExchangeRateModSlice {
				shouldUpdate := false
				updateMods := make(factory.ExchangeRateModSlice, 0, 4)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewExchangeRateWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.ExchangeRateModSlice{
					factory.ExchangeRateMods.Source(obj.Source),
					factory.ExchangeRateMods.BaseCurrency(obj.BaseCurrency),
					factory.ExchangeRateMods.QuoteCurrency(obj.QuoteCurrency),
					factory.ExchangeRateMods.EffectiveDate(obj.EffectiveDate),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewExchangeRateWithContext(ctx, factory.ExchangeRateMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewExchangeRateWithContext(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewExchangeRateWithContext(ctx, tt.conflictMods(ctx, t, exec, obj)...).BuildSetter())
			if !errors.Is(ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
