// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/gofrs/uuid/v5"
	models "github.com/goguson/homework-april-1/internal/db/bob/bob"
	"github.com/shopspring/decimal"
)

type Factory struct {
	baseExchangeRateMods ExchangeRateModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewExchangeRate(mods ...ExchangeRateMod) *ExchangeRateTemplate {
	return f.NewExchangeRateWithContext(context.Background(), mods...)
}

func (f *Factory) NewExchangeRateWithContext(ctx context.Context, mods ...ExchangeRateMod) *ExchangeRateTemplate {
	o := &ExchangeRateTemplate{f: f}

	if f != nil {
		f.baseExchangeRateMods.Apply(ctx, o)
	}

	ExchangeRateModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingExchangeRate(m *models.ExchangeRate) *ExchangeRateTemplate {
	o := &ExchangeRateTemplate{f: f, alreadyPersisted: true}

	o.ID = func() uuid.UUID { return m.ID }
	o.BaseCurrency = func() string { return m.BaseCurrency }
	o.QuoteCurrency = func() string { return m.QuoteCurrency }
	o.Rate = func() decimal.Decimal { return m.Rate }
	o.EffectiveDate = func() time.Time { return m.EffectiveDate }
	o.Source = func() string { return m.Source }
	o.SourcePublishedAt = func() null.Val[time.Time] { return m.SourcePublishedAt }
	o.CreatedAt = func() time.Time { return m.CreatedAt }

	return o
}

func (f *Factory) ClearBaseExchangeRateMods() {
	f.baseExchangeRateMods = nil
}

func (f *Factory) AddBaseExchangeRateMod(mods ...ExchangeRateMod) {
	f.baseExchangeRateMods = append(f.baseExchangeRateMods, mods...)
}
