// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	models "github.com/goguson/homework-april-1/internal/db/bob/bob"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type ExchangeRateMod interface {
	Apply(context.Context, *ExchangeRateTemplate)
}

type ExchangeRateModFunc func(context.Context, *ExchangeRateTemplate)

func (f ExchangeRateModFunc) Apply(ctx context.Context, n *ExchangeRateTemplate) {
	f(ctx, n)
}

type ExchangeRateModSlice []ExchangeRateMod

func (mods ExchangeRateModSlice) Apply(ctx context.Context, n *ExchangeRateTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ExchangeRateTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ExchangeRateTemplate struct {
	ID                func() uuid.UUID
	BaseCurrency      func() string
	QuoteCurrency     func() string
	Rate              func() decimal.Decimal
	EffectiveDate     func() time.Time
	Source            func() string
	SourcePublishedAt func() null.Val[time.Time]
	CreatedAt         func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the ExchangeRateTemplate
func (o *ExchangeRateTemplate) Apply(ctx context.Context, mods ...ExchangeRateMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ExchangeRate
// according to the relationships in the template. Nothing is inserted into the db
func (t ExchangeRateTemplate) setModelRels(o *models.ExchangeRate) {}

// BuildSetter returns an *models.ExchangeRateSetter
// this does nothing with the relationship templates
func (o ExchangeRateTemplate) BuildSetter() *models.ExchangeRateSetter {
	m := &models.ExchangeRateSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.BaseCurrency != nil {
		val := o.BaseCurrency()
		m.BaseCurrency = omit.From(val)
	}
	if o.QuoteCurrency != nil {
		val := o.QuoteCurrency()
		m.QuoteCurrency = omit.From(val)
	}
	if o.Rate != nil {
		val := o.Rate()
		m.Rate = omit.From(val)
	}
	if o.EffectiveDate != nil {
		val := o.EffectiveDate()
		m.EffectiveDate = omit.From(val)
	}
	if o.Source != nil {
		val := o.Source()
		m.Source = omit.From(val)
	}
	if o.SourcePublishedAt != nil {
		val := o.SourcePublishedAt()
		m.SourcePublishedAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ExchangeRateSetter
// this does nothing with the relationship templates
func (o ExchangeRateTemplate) BuildManySetter(number int) []*models.ExchangeRateSetter {
	m := make([]*models.ExchangeRateSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ExchangeRate
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ExchangeRateTemplate.Create
func (o ExchangeRateTemplate) Build() *models.ExchangeRate {
	m := &models.ExchangeRate{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.BaseCurrency != nil {
		m.BaseCurrency = o.BaseCurrency()
	}
	if o.QuoteCurrency != nil {
		m.QuoteCurrency = o.QuoteCurrency()
	}
	if o.Rate != nil {
		m.Rate = o.Rate()
	}
	if o.EffectiveDate != nil {
		m.EffectiveDate = o.EffectiveDate()
	}
	if o.Source != nil {
		m.Source = o.Source()
	}
	if o.SourcePublishedAt != nil {
		m.SourcePublishedAt = o.SourcePublishedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ExchangeRateSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ExchangeRateTemplate.CreateMany
func (o ExchangeRateTemplate) BuildMany(number int) models.ExchangeRateSlice {
	m := make(models.ExchangeRateSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableExchangeRate(m *models.ExchangeRateSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.QuoteCurrency.IsValue()) {
		val := random_string(nil, "3")
		m.QuoteCurrency = omit.From(val)
	}
	if !(m.Rate.IsValue()) {
		val := random_decimal_Decimal(nil, "20", "8")
		m.Rate = omit.From(val)
	}
	if !(m.EffectiveDate.IsValue()) {
		val := random_time_Time(nil)
		m.EffectiveDate = omit.From(val)
	}
	if !(m.Source.IsValue()) {
		val := random_string(nil)
		m.Source = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ExchangeRate
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ExchangeRateTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ExchangeRate) error {
	var err error

	return err
}

// Create builds a exchangeRate and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ExchangeRateTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ExchangeRate, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableExchangeRate(opt)

	m, err := models.ExchangeRates.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a exchangeRate and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ExchangeRateTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ExchangeRate {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a exchangeRate and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ExchangeRateTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ExchangeRate {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple exchangeRates and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ExchangeRateTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ExchangeRateSlice, error) {
	var err error
	m := make(models.ExchangeRateSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple exchangeRates and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ExchangeRateTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ExchangeRateSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple exchangeRates and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ExchangeRateTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ExchangeRateSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ExchangeRate has methods that act as mods for the ExchangeRateTemplate
var ExchangeRateMods exchangeRateMods

type exchangeRateMods struct{}

func (m exchangeRateMods) RandomizeAllColumns(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModSlice{
		ExchangeRateMods.RandomID(f),
		ExchangeRateMods.RandomBaseCurrency(f),
		ExchangeRateMods.RandomQuoteCurrency(f),
		ExchangeRateMods.RandomRate(f),
		ExchangeRateMods.RandomEffectiveDate(f),
		ExchangeRateMods.RandomSource(f),
		ExchangeRateMods.RandomSourcePublishedAt(f),
		ExchangeRateMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m exchangeRateMods) ID(val uuid.UUID) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m exchangeRateMods) IDFunc(f func() uuid.UUID) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m exchangeRateMods) UnsetID() ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m exchangeRateMods) RandomID(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m exchangeRateMods) BaseCurrency(val string) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.BaseCurrency = func() string { return val }
	})
}

// Set the Column from the function
func (m exchangeRateMods) BaseCurrencyFunc(f func() string) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.BaseCurrency = f
	})
}

// Clear any values for the column
func (m exchangeRateMods) UnsetBaseCurrency() ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.BaseCurrency = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m exchangeRateMods) RandomBaseCurrency(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.BaseCurrency = func() string {
			return random_string(f, "3")
		}
	})
}

// Set the model columns to this value
func (m exchangeRateMods) QuoteCurrency(val string) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.QuoteCurrency = func() string { return val }
	})
}

// Set the Column from the function
func (m exchangeRateMods) QuoteCurrencyFunc(f func() string) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.QuoteCurrency = f
	})
}

// Clear any values for the column
func (m exchangeRateMods) UnsetQuoteCurrency() ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.QuoteCurrency = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m exchangeRateMods) RandomQuoteCurrency(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.QuoteCurrency = func() string {
			return random_string(f, "3")
		}
	})
}

// Set the model columns to this value
func (m exchangeRateMods) Rate(val decimal.Decimal) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.Rate = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m exchangeRateMods) RateFunc(f func() decimal.Decimal) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.Rate = f
	})
}

// Clear any values for the column
func (m exchangeRateMods) UnsetRate() ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.Rate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m exchangeRateMods) RandomRate(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.Rate = func() decimal.Decimal {
			return random_decimal_Decimal(f, "20", "8")
		}
	})
}

// Set the model columns to this value
func (m exchangeRateMods) EffectiveDate(val time.Time) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.EffectiveDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m exchangeRateMods) EffectiveDateFunc(f func() time.Time) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.EffectiveDate = f
	})
}

// Clear any values for the column
func (m exchangeRateMods) UnsetEffectiveDate() ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.EffectiveDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m exchangeRateMods) RandomEffectiveDate(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.EffectiveDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m exchangeRateMods) Source(val string) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.Source = func() string { return val }
	})
}

// Set the Column from the function
func (m exchangeRateMods) SourceFunc(f func() string) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.Source = f
	})
}

// Clear any values for the column
func (m exchangeRateMods) UnsetSource() ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.Source = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m exchangeRateMods) RandomSource(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.Source = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m exchangeRateMods) SourcePublishedAt(val null.Val[time.Time]) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.SourcePublishedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m exchangeRateMods) SourcePublishedAtFunc(f func() null.Val[time.Time]) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.SourcePublishedAt = f
	})
}

// Clear any values for the column
func (m exchangeRateMods) UnsetSourcePublishedAt() ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.SourcePublishedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m exchangeRateMods) RandomSourcePublishedAt(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.SourcePublishedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m exchangeRateMods) RandomSourcePublishedAtNotNull(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.SourcePublishedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m exchangeRateMods) CreatedAt(val time.Time) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m exchangeRateMods) CreatedAtFunc(f func() time.Time) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m exchangeRateMods) UnsetCreatedAt() ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m exchangeRateMods) RandomCreatedAt(f *faker.Faker) ExchangeRateMod {
	return ExchangeRateModFunc(func(_ context.Context, o *ExchangeRateTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m exchangeRateMods) WithParentsCascading() ExchangeRateMod {
	return ExchangeRateModFunc(func(ctx context.Context, o *ExchangeRateTemplate) {
		if isDone, _ := exchangeRateWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = exchangeRateWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
