// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ExchangeRates = Table[
	exchangeRateColumns,
	exchangeRateIndexes,
	exchangeRateForeignKeys,
	exchangeRateUniques,
	exchangeRateChecks,
]{
	Schema: "",
	Name:   "exchange_rates",
	Columns: exchangeRateColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		BaseCurrency: column{
			Name:      "base_currency",
			DBType:    "character",
			Default:   "'EUR'::bpchar",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		QuoteCurrency: column{
			Name:      "quote_currency",
			DBType:    "character",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Rate: column{
			Name:      "rate",
			DBType:    "numeric",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		EffectiveDate: column{
			Name:      "effective_date",
			DBType:    "date",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Source: column{
			Name:      "source",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SourcePublishedAt: column{
			Name:      "source_published_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: exchangeRateIndexes{
		ExchangeRatesPkey: index{
			Type: "btree",
			Name: "exchange_rates_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		ExchangeRatesQuoteCurrencyEffectiveDateIdx: index{
			Type: "btree",
			Name: "exchange_rates_quote_currency_effective_date_idx",
			Columns: []indexColumn{
				{
					Name:         "quote_currency",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "effective_date",
					Desc:         null.FromCond(true, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false, true},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		ExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey: index{
			Type: "btree",
			Name: "exchange_rates_source_base_currency_quote_currency_effectiv_key",
			Columns: []indexColumn{
				{
					Name:         "source",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "base_currency",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "quote_currency",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "effective_date",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false, false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "exchange_rates_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: exchangeRateUniques{
		ExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey: constraint{
			Name:    "exchange_rates_source_base_currency_quote_currency_effectiv_key",
			Columns: []string{"source", "base_currency", "quote_currency", "effective_date"},
			Comment: "",
		},
	},

	Comment: "",
}

type exchangeRateColumns struct {
	ID                column
	BaseCurrency      column
	QuoteCurrency     column
	Rate              column
	EffectiveDate     column
	Source            column
	SourcePublishedAt column
	CreatedAt         column
}

func (c exchangeRateColumns) AsSlice() []column {
	return []column{
		c.ID, c.BaseCurrency, c.QuoteCurrency, c.Rate, c.EffectiveDate, c.Source, c.SourcePublishedAt, c.CreatedAt,
	}
}

type exchangeRateIndexes struct {
	ExchangeRatesPkey                                       index
	ExchangeRatesQuoteCurrencyEffectiveDateIdx              index
	ExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey index
}

func (i exchangeRateIndexes) AsSlice() []index {
	return []index{
		i.ExchangeRatesPkey, i.ExchangeRatesQuoteCurrencyEffectiveDateIdx, i.ExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey,
	}
}

type exchangeRateForeignKeys struct{}

func (f exchangeRateForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type exchangeRateUniques struct {
	ExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey constraint
}

func (u exchangeRateUniques) AsSlice() []constraint {
	return []constraint{
		u.ExchangeRatesSourceBaseCurrencyQuoteCurrencyEffectivKey,
	}
}

type exchangeRateChecks struct{}

func (c exchangeRateChecks) AsSlice() []check {
	return []check{}
}
