// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// ExchangeRate is an object representing the database table.
type ExchangeRate struct {
	ID                uuid.UUID           `db:"id,pk" `
	BaseCurrency      string              `db:"base_currency" `
	QuoteCurrency     string              `db:"quote_currency" `
	Rate              decimal.Decimal     `db:"rate" `
	EffectiveDate     time.Time           `db:"effective_date" `
	Source            string              `db:"source" `
	SourcePublishedAt null.Val[time.Time] `db:"source_published_at" `
	CreatedAt         time.Time           `db:"created_at" `
}

// ExchangeRateSlice is an alias for a slice of pointers to ExchangeRate.
// This should almost always be used instead of []*ExchangeRate.
type ExchangeRateSlice []*ExchangeRate

// ExchangeRates contains methods to work with the exchange_rates table
var ExchangeRates = psql.NewTablex[*ExchangeRate, ExchangeRateSlice, *ExchangeRateSetter]("", "exchange_rates", buildExchangeRateColumns("exchange_rates"))

// ExchangeRatesQuery is a query on the exchange_rates table
type ExchangeRatesQuery = *psql.ViewQuery[*ExchangeRate, ExchangeRateSlice]

func buildExchangeRateColumns(tableName string) exchangeRateColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "base_currency", "quote_currency", "rate", "effective_date", "source", "source_published_at", "created_at",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return exchangeRateColumns{
		ColumnsExpr:       columnsExpr,
		tableAlias:        tableName,
		ID:                psql.Quote(tableName, "id"),
		BaseCurrency:      psql.Quote(tableName, "base_currency"),
		QuoteCurrency:     psql.Quote(tableName, "quote_currency"),
		Rate:              psql.Quote(tableName, "rate"),
		EffectiveDate:     psql.Quote(tableName, "effective_date"),
		Source:            psql.Quote(tableName, "source"),
		SourcePublishedAt: psql.Quote(tableName, "source_published_at"),
		CreatedAt:         psql.Quote(tableName, "created_at"),
	}
}

type exchangeRateColumns struct {
	expr.ColumnsExpr
	tableAlias        string
	ID                psql.Expression
	BaseCurrency      psql.Expression
	QuoteCurrency     psql.Expression
	Rate              psql.Expression
	EffectiveDate     psql.Expression
	Source            psql.Expression
	SourcePublishedAt psql.Expression
	CreatedAt         psql.Expression
}

func (c exchangeRateColumns) Alias() string {
	return c.tableAlias
}

func (exchangeRateColumns) AliasedAs(tableName string) exchangeRateColumns {
	return buildExchangeRateColumns(tableName)
}

func (c exchangeRateColumns) Unqualified() exchangeRateColumns {
	return buildExchangeRateColumns("")
}

// ExchangeRateSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ExchangeRateSetter struct {
	ID                omit.Val[uuid.UUID]       `db:"id,pk" `
	BaseCurrency      omit.Val[string]          `db:"base_currency" `
	QuoteCurrency     omit.Val[string]          `db:"quote_currency" `
	Rate              omit.Val[decimal.Decimal] `db:"rate" `
	EffectiveDate     omit.Val[time.Time]       `db:"effective_date" `
	Source            omit.Val[string]          `db:"source" `
	SourcePublishedAt omitnull.Val[time.Time]   `db:"source_published_at" `
	CreatedAt         omit.Val[time.Time]       `db:"created_at" `
}

func (s ExchangeRateSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.BaseCurrency.IsValue() {
		vals = append(vals, "base_currency")
	}
	if s.QuoteCurrency.IsValue() {
		vals = append(vals, "quote_currency")
	}
	if s.Rate.IsValue() {
		vals = append(vals, "rate")
	}
	if s.EffectiveDate.IsValue() {
		vals = append(vals, "effective_date")
	}
	if s.Source.IsValue() {
		vals = append(vals, "source")
	}
	if !s.SourcePublishedAt.IsUnset() {
		vals = append(vals, "source_published_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s ExchangeRateSetter) Overwrite(t *ExchangeRate) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.BaseCurrency.IsValue() {
		t.BaseCurrency = s.BaseCurrency.MustGet()
	}
	if s.QuoteCurrency.IsValue() {
		t.QuoteCurrency = s.QuoteCurrency.MustGet()
	}
	if s.Rate.IsValue() {
		t.Rate = s.Rate.MustGet()
	}
	if s.EffectiveDate.IsValue() {
		t.EffectiveDate = s.EffectiveDate.MustGet()
	}
	if s.Source.IsValue() {
		t.Source = s.Source.MustGet()
	}
	if !s.SourcePublishedAt.IsUnset() {
		t.SourcePublishedAt = s.SourcePublishedAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *ExchangeRateSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ExchangeRates.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.BaseCurrency.IsValue() {
			vals[1] = psql.Arg(s.BaseCurrency.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.QuoteCurrency.IsValue() {
			vals[2] = psql.Arg(s.QuoteCurrency.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Rate.IsValue() {
			vals[3] = psql.Arg(s.Rate.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.EffectiveDate.IsValue() {
			vals[4] = psql.Arg(s.EffectiveDate.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Source.IsValue() {
			vals[5] = psql.Arg(s.Source.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.SourcePublishedAt.IsUnset() {
			vals[6] = psql.Arg(s.SourcePublishedAt.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[7] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ExchangeRateSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ExchangeRateSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.BaseCurrency.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "base_currency")...),
			psql.Arg(s.BaseCurrency),
		}})
	}

	if s.QuoteCurrency.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "quote_currency")...),
			psql.Arg(s.QuoteCurrency),
		}})
	}

	if s.Rate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "rate")...),
			psql.Arg(s.Rate),
		}})
	}

	if s.EffectiveDate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "effective_date")...),
			psql.Arg(s.EffectiveDate),
		}})
	}

	if s.Source.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "source")...),
			psql.Arg(s.Source),
		}})
	}

	if !s.SourcePublishedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "source_published_at")...),
			psql.Arg(s.SourcePublishedAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindExchangeRate retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindExchangeRate(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*ExchangeRate, error) {
	if len(cols) == 0 {
		return ExchangeRates.Query(
			sm.Where(ExchangeRates.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ExchangeRates.Query(
		sm.Where(ExchangeRates.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(ExchangeRates.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ExchangeRateExists checks the presence of a single record by primary key
func ExchangeRateExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return ExchangeRates.Query(
		sm.Where(ExchangeRates.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ExchangeRate is retrieved from the database
func (o *ExchangeRate) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ExchangeRates.AfterSelectHooks.RunHooks(ctx, exec, ExchangeRateSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ExchangeRates.AfterInsertHooks.RunHooks(ctx, exec, ExchangeRateSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ExchangeRates.AfterUpdateHooks.RunHooks(ctx, exec, ExchangeRateSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ExchangeRates.AfterDeleteHooks.RunHooks(ctx, exec, ExchangeRateSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = ExchangeRates.AfterMergeHooks.RunHooks(ctx, exec, ExchangeRateSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ExchangeRate
func (o *ExchangeRate) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *ExchangeRate) pkEQ() dialect.Expression {
	return psql.Quote("exchange_rates", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ExchangeRate
func (o *ExchangeRate) Update(ctx context.Context, exec bob.Executor, s *ExchangeRateSetter) error {
	v, err := ExchangeRates.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single ExchangeRate record with an executor
func (o *ExchangeRate) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ExchangeRates.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ExchangeRate using the executor
func (o *ExchangeRate) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ExchangeRates.Query(
		sm.Where(ExchangeRates.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ExchangeRateSlice is retrieved from the database
func (o ExchangeRateSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ExchangeRates.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ExchangeRates.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ExchangeRates.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ExchangeRates.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = ExchangeRates.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ExchangeRateSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("exchange_rates", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ExchangeRateSlice) copyMatchingRows(from ...*ExchangeRate) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ExchangeRateSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ExchangeRates.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ExchangeRate:
				o.copyMatchingRows(retrieved)
			case []*ExchangeRate:
				o.copyMatchingRows(retrieved...)
			case ExchangeRateSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ExchangeRate or a slice of ExchangeRate
				// then run the AfterUpdateHooks on the slice
				_, err = ExchangeRates.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ExchangeRateSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ExchangeRates.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ExchangeRate:
				o.copyMatchingRows(retrieved)
			case []*ExchangeRate:
				o.copyMatchingRows(retrieved...)
			case ExchangeRateSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ExchangeRate or a slice of ExchangeRate
				// then run the AfterDeleteHooks on the slice
				_, err = ExchangeRates.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o ExchangeRateSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ExchangeRates.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ExchangeRate:
				o.copyMatchingRows(retrieved)
			case []*ExchangeRate:
				o.copyMatchingRows(retrieved...)
			case ExchangeRateSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ExchangeRate or a slice of ExchangeRate
				// then run the AfterMergeHooks on the slice
				_, err = ExchangeRates.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o ExchangeRateSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ExchangeRateSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ExchangeRates.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ExchangeRateSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ExchangeRates.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ExchangeRateSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ExchangeRates.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type exchangeRateWhere[Q psql.Filterable] struct {
	ID                psql.WhereMod[Q, uuid.UUID]
	BaseCurrency      psql.WhereMod[Q, string]
	QuoteCurrency     psql.WhereMod[Q, string]
	Rate              psql.WhereMod[Q, decimal.Decimal]
	EffectiveDate     psql.WhereMod[Q, time.Time]
	Source            psql.WhereMod[Q, string]
	SourcePublishedAt psql.WhereNullMod[Q, time.Time]
	CreatedAt         psql.WhereMod[Q, time.Time]
}

func (exchangeRateWhere[Q]) AliasedAs(alias string) exchangeRateWhere[Q] {
	return buildExchangeRateWhere[Q](buildExchangeRateColumns(alias))
}

func buildExchangeRateWhere[Q psql.Filterable](cols exchangeRateColumns) exchangeRateWhere[Q] {
	return exchangeRateWhere[Q]{
		ID:                psql.Where[Q, uuid.UUID](cols.ID),
		BaseCurrency:      psql.Where[Q, string](cols.BaseCurrency),
		QuoteCurrency:     psql.Where[Q, string](cols.QuoteCurrency),
		Rate:              psql.Where[Q, decimal.Decimal](cols.Rate),
		EffectiveDate:     psql.Where[Q, time.Time](cols.EffectiveDate),
		Source:            psql.Where[Q, string](cols.Source),
		SourcePublishedAt: psql.WhereNull[Q, time.Time](cols.SourcePublishedAt),
		CreatedAt:         psql.Where[Q, time.Time](cols.CreatedAt),
	}
}
